'use strict';
const KEY=window.LITTLE_STEPS_CONFIG.storageKey;
const uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
const templates=[{name:'School morning',icon:'☀️',tone:'morning',steps:[['👕','Get dressed',5],['🥣','Eat breakfast',10],['🪥','Brush teeth',2],['👟','Put shoes on',3],['🎒','Pick up backpack',2]]},{name:'After school',icon:'🎒',tone:'afternoon',steps:[['🎒','Put your bag away',2],['🍎','Have a snack',10],['🌳','Take a play break',15],['📖','Choose one small task',10]]},{name:'Ready for bed',icon:'🌙',tone:'evening',steps:[['🧸','Put pajamas on',5],['🪥','Brush teeth',2],['🎒','Get tomorrow’s things ready',5],['📚','Share a story',10]]}];
function makeRoutines(){return templates.map(t=>({...t,id:uid(),steps:t.steps.map(([icon,label,minutes])=>({id:uid(),icon,label,minutes}))}))}
function makeChild(name='My child'){return {id:uid(),name,routines:makeRoutines(),stars:0,earned:[],history:[],rewards:[{id:uid(),name:'Choose a family game',cost:10,icon:'🎲'}],redemptions:[]}}
const initial=()=>{const child=makeChild();return {version:1,children:[child],selected:child.id,settings:{timer:true,readAloud:false},session:null}};
let state,saveError=false,loadError=false;
try{const raw=localStorage.getItem(KEY);state=raw?validate(JSON.parse(raw)):initial()}catch(e){state=initial();loadError=true}
let view='routines',chartId=null,draft=null,finish=null,parentUnlocked=false;
const app=document.getElementById('app'),modal=document.getElementById('modal');
function child(){return state.children.find(c=>c.id===state.selected)||state.children[0]}
function routine(id){return child().routines.find(r=>r.id===id)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));saveError=false}catch(e){saveError=true;toast('This browser could not save. Export a backup from Parent settings.')}}
function toast(s){const el=document.getElementById('toast');el.textContent=s;el.style.display='block';clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>el.style.display='none',4500)}
function brand(){return '<div class="brand"><span class="brand-mark">✦</span><span>little steps<small>BY KEPTAPPS</small></span></div>'}
function button(label,action,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`}
function render(){
 if(state.session){renderPlayer();return}if(finish){renderFinish();return}
 const c=child();app.innerHTML=`<header>${brand()}<nav aria-label="Main navigation">${[['routines','My routines'],['rewards','Rewards'],['charts','Print charts'],['settings','Parent settings']].map(([v,n])=>button(n,'navigate',view===v?'active':'',`data-view="${v}"`)).join('')}</nav><label><span class="sr-only">Choose child</span><select class="profile-select" id="profile">${state.children.map(p=>`<option value="${esc(p.id)}" ${p.id===c.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label></header><main>${loadError?'<p class="warning">Saved data could not be read. You can restore a backup in Parent settings. Changes will replace the unreadable local data.</p>':''}${saveError?'<p class="warning">Changes are not being saved. Please export a backup.</p>':''}${view==='routines'?home():view==='rewards'?rewards():view==='charts'?charts():settings()}<p class="footnote no-print">Little steps count. Every day is a fresh start.<br>Saved in this browser · Export a backup to keep your routines safe.</p></main>`;
}
function home(){const c=child();const today=c.history.filter(h=>h.date===day());return `<div class="page-heading"><div><p class="eyebrow">A little structure. A lot of possibility.</p><h1>${esc(c.name)}’s routines</h1><p>One small step, then the next.</p></div>${button('+ Add routine','new-routine','soft')}</div><div class="layout"><section><div class="welcome"><div><span class="pill">✦ Meet Milo, your routine buddy</span><h2 style="margin-top:16px">We can do this.<br>One step at a time.</h2><p>Pick a routine below. Milo will come along.</p></div><img class="pet" src="companion.png" alt="Milo, a smiling blue companion holding a star"></div><div class="section-row"><h2>Let’s find our next step</h2><span class="note">${c.routines.length} routines</span></div><div class="cards">${c.routines.map(r=>`<article class="routine-card"><div class="routine-icon ${esc(r.tone)}">${esc(r.icon)}</div><div><h3>${esc(r.name)}</h3><p>${r.steps.length} steps · about ${r.steps.reduce((n,s)=>n+s.minutes,0)} min ${today.some(h=>h.routineId===r.id)?'· Tried today ✓':''}</p></div><div class="card-actions">${button('Edit','edit-routine','icon-btn',`data-id="${r.id}" aria-label="Edit ${esc(r.name)}"`)}${button('Let’s go →','start','primary',`data-id="${r.id}"`)}</div></article>`).join('')||'<div class="panel empty">Add a routine to start your first little step.</div>'}</div></section><aside class="aside"><div class="aside-card"><p class="eyebrow">Little wins</p><h2>Your star jar</h2><div class="stars">★ ${c.stars} <small>stars to spend</small></div><p class="note">One star for each step you finish. No stars lost for taking your time.</p>${c.rewards[0]?`<div class="progress"><span style="width:${Math.min(100,c.stars/c.rewards[0].cost*100)}%"></span></div><p class="note">${esc(c.rewards[0].name)} · ${c.rewards[0].cost} stars</p>`:''}${button('See rewards','navigate','soft full','data-view="rewards"')}</div><div class="aside-card"><h3>A gentle start</h3><ul class="mini-list"><li>☝️ Start with one short routine</li><li>⏸ Take a break when you need one</li><li>💙 Ask a grown-up for help</li></ul></div></aside></div>`}
function rewards(){const c=child();return `<div class="page-heading"><div><p class="eyebrow">Celebrate the small things</p><h1>Your little wins</h1><p>Choose rewards together with a grown-up.</p></div><div class="pill">★ ${c.stars} stars</div></div><div class="grid-two"><section class="panel"><div class="section-row"><h2>Something to look forward to</h2>${button('+ Add','add-reward','small soft')}</div>${c.rewards.map(r=>`<article class="reward-card"><span class="icon">${esc(r.icon)}</span><div class="body"><h3>${esc(r.name)}</h3><p>${r.cost} stars</p></div>${button(c.stars>=r.cost?'Ask to redeem':`${r.cost-c.stars} to go`,'redeem',c.stars>=r.cost?'primary':'soft',`data-id="${r.id}" ${c.stars<r.cost?'disabled':''}`)}${button('Remove','remove-reward','small icon-btn',`data-id="${r.id}"`)}</article>`).join('')||'<p>Add a small reward your child would enjoy.</p>'}<p class="note">A grown-up approves each redemption. Rewards are optional; your routines work without them.</p></section><section class="panel"><h2>Recent routines</h2>${c.history.length?`<ul class="mini-list">${c.history.slice(-8).reverse().map(h=>`<li><strong>${esc(h.name)}</strong><br><span class="muted">${esc(h.displayDate)} · ${h.done}/${h.total} steps · ${h.stars} new stars</span></li>`).join('')}</ul>`:'<div class="empty">Your first little win is waiting.<br>Finish a routine to see it here.</div>'}${c.redemptions.length?`<h3 style="margin-top:22px">Rewards redeemed</h3><ul class="mini-list">${c.redemptions.slice(-5).reverse().map(r=>`<li>${esc(r.name)} · ${esc(r.date)}</li>`).join('')}</ul>`:''}</section></div>`}
function charts(){const c=child();const r=routine(chartId)||c.routines[0];return `<div class="page-heading"><div><p class="eyebrow">A screen-free option</p><h1>Take your routine with you</h1><p class="no-print">Print a matching chart for the fridge, bedroom or school bag.</p></div>${r?button('Print / save PDF','print','primary'):''}</div>${r?`<div class="field no-print"><label for="chart-select">Choose a routine</label><select id="chart-select">${c.routines.map(x=>`<option value="${x.id}" ${r.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><section class="panel print-chart"><p class="eyebrow">LITTLE STEPS · ${esc(c.name)}</p><h2>${esc(r.icon)} ${esc(r.name)}</h2><p>One step at a time. Ask for help whenever you need it.</p><ul class="checklist">${r.steps.map(s=>`<li><span class="box"></span><span class="emoji">${esc(s.icon)}</span><strong>${esc(s.label)}</strong><small>${s.minutes} min</small></li>`).join('')}</ul><p class="note">The times are gentle guides. Taking longer is okay.<br>Little Steps by KeptApps · Personal family use</p></section>`:'<p>Add a routine first to make a printable chart.</p>'}`}
function settings(){const c=child();return `<div class="page-heading"><div><p class="eyebrow">Made to fit your family</p><h1>Parent settings</h1><p>Start small. You can change everything as you go.</p></div></div><div class="grid-two"><section class="panel"><h2>Your children</h2><form id="child-form"><div class="field"><label for="child-name">Current child’s nickname</label><input id="child-name" name="name" maxlength="35" value="${esc(c.name)}" required autocomplete="off"></div>${button('Save name','save-name','primary','type="submit"')}</form><div class="row" style="margin-top:18px">${button('+ Add child','add-child','soft')}${state.children.length>1?button('Remove this profile','delete-child','danger small'):''}</div><p class="note" style="margin-top:16px">A nickname is enough. Each child has separate routines, stars and rewards.</p><h2 style="margin-top:30px">Routine preferences</h2><label class="check"><input type="checkbox" id="timer-setting" ${state.settings.timer?'checked':''}> Show the visual timer</label><label class="check"><input type="checkbox" id="voice-setting" ${state.settings.readAloud?'checked':''}> Read each step aloud</label><p class="note">Voice availability depends on your browser. You can also use “Read to me” during a routine. Sounds are never required.</p></section><section class="panel"><h2>Keep your routines safe</h2><p>Profiles and progress are saved only in this browser. They do not automatically sync between devices. Clearing browser data can remove them.</p><div class="row">${button('Export backup','export','primary')}${button('Restore backup','restore','soft')}</div><input type="file" id="import-file" accept=".json,application/json" hidden><p class="note" style="margin-top:18px">Use a backup to move your routines to another device. Restoring replaces the profiles and progress on this device.</p><h2 style="margin-top:30px">About Little Steps</h2><p class="note">A parent-guided planning aid designed for children around ages 5–10. It is not an ADHD assessment or treatment. Adjust routines to your child’s needs.</p><p class="note">The grown-up question helps prevent accidental changes; it is not a secure parental lock. Keep a grown-up nearby when your child needs support.</p><p class="note">Stars are awarded once per step per day, so replaying a routine is welcome without adding duplicate stars.</p></section></div>`}
function showModal(html){modal.innerHTML=button('×','close','close-dialog icon-btn','aria-label="Close dialog"')+html;if(!modal.open)modal.showModal()}
function gate(callback){if(parentUnlocked){callback();return}showModal(`<h2>A quick grown-up check</h2><p>Ask a grown-up to help with this part.</p><form id="gate-form"><div class="field"><label for="gate-answer">What is 7 + 8?</label><input id="gate-answer" inputmode="numeric" required autocomplete="off"></div><p id="gate-error" role="alert"></p><button class="primary" type="submit">Continue</button></form>`);document.getElementById('gate-form').onsubmit=e=>{e.preventDefault();if(document.getElementById('gate-answer').value.trim()!=='15'){document.getElementById('gate-error').textContent='Ask your grown-up to try again.';return}parentUnlocked=true;modal.close();callback()}}
function start(id){const r=routine(id);if(!r||!r.steps.length)return;parentUnlocked=false;finish=null;state.session={childId:child().id,routineId:id,index:0,done:0,newStars:0,startedDate:day(),completed:[],paused:false,remaining:r.steps[0].minutes*60,deadline:Date.now()+r.steps[0].minutes*60000,help:false};save();render();speakStep()}
function current(){const s=state.session;if(!s)return null;const r=routine(s.routineId);if(!r)return null;return {s,r,step:r.steps[s.index]}}
function seconds(){const {s}=current();return Math.max(0,s.paused?s.remaining:Math.ceil((s.deadline-Date.now())/1000))}
function renderPlayer(){const cur=current();if(!cur||!cur.step){state.session=null;save();render();return}const {s,r,step}=cur;app.innerHTML=`<div class="kid-shell"><div class="kid-top">${brand()}${button('Grown-up / exit','exit','soft')}</div><div class="kid-progress"><div class="row spread"><strong>${esc(r.name)}</strong><span class="note">Step ${s.index+1} of ${r.steps.length}</span></div><div class="progress"><span style="width:${s.index/r.steps.length*100}%"></span></div></div><main class="kid-card"><div class="eyebrow">Right now</div><div class="task-picture" role="img" aria-label="${esc(step.label)}">${esc(step.icon)}</div><h1>${esc(step.label)}</h1>${state.settings.timer?`<div class="timer" id="timer" aria-label="Time remaining"></div><div class="timer-bar"><span id="timer-fill"></span></div><p class="note" id="timer-note"></p><div class="row" style="justify-content:center">${button(s.paused?'▶ Resume':'Ⅱ Pause','pause','small soft')}${button('+ 1 minute','add-time','small soft')}</div>`:'<p>Take the time you need.</p>'}${button('I did it! ✓','done','primary done')}<div class="row" style="justify-content:center">${button('I need help','help','soft')}${button('Read to me','read','soft small')}${button('Skip for now','skip','icon-btn small')}</div>${s.help?'<div class="help" role="status"><strong>Let’s ask a grown-up.</strong><p style="margin:6px 0 0">We can do this together. Your timer is paused.</p></div>':''}<div class="next"><span class="muted">Up next</span> &nbsp; ${s.index+1<r.steps.length?`${esc(r.steps[s.index+1].icon)} ${esc(r.steps[s.index+1].label)}`:'✦ Celebrate your little steps'}</div></main><div class="kid-pet"><img src="companion.png" alt="Milo"><p>${s.help?'Asking for help is a good step.':'I’m right here with you.'}</p></div></div>`;tick()}
function tick(){if(!state.session||!current()?.step)return;const n=seconds(),el=document.getElementById('timer');if(el){el.textContent=`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;const {step}=current();document.getElementById('timer-fill').style.width=Math.min(100,n/(step.minutes*60)*100)+'%';document.getElementById('timer-note').textContent=n===0?'Need longer? That’s okay.':state.session.paused?'Paused. Take a little breather.':'A gentle guide, not a race.'}}
setInterval(tick,500);
function advance(done){const {s,r,step}=current();if(done){s.done++;s.completed.push(step.id);const token=`${s.startedDate}:${r.id}:${step.id}`;if(!child().earned.includes(token)){child().earned.push(token);child().stars++;s.newStars++}}s.index++;if(s.index>=r.steps.length){const h={date:day(),displayDate:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'}),routineId:r.id,name:r.name,done:s.done,total:r.steps.length,stars:s.newStars};child().history.push(h);child().history=child().history.slice(-100);finish=h;state.session=null;if('speechSynthesis'in window)speechSynthesis.cancel();save();render();return}s.remaining=r.steps[s.index].minutes*60;s.deadline=Date.now()+s.remaining*1000;s.paused=false;s.help=false;save();render();speakStep()}
function renderFinish(){app.innerHTML=`<div class="kid-shell"><div class="kid-top">${brand()}</div><main class="kid-card" style="margin-top:40px"><img class="celebrate" src="companion.png" alt="Milo celebrating your effort"><p class="eyebrow">Every little step counts</p><h1>${finish.done===finish.total?'You did it!':'You showed up!'}</h1><p>${finish.done} of ${finish.total} steps finished. ${finish.done<finish.total?'You can try the others another time.':'Time to enjoy your little win.'}</p><div class="stars">★ +${finish.stars} <small>new stars</small></div>${button('Back to my routines','finish','primary full')}</main></div>`}
function readStep(){if(!('speechSynthesis'in window)){toast('Read-aloud is not available in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current().step.label);u.rate=.85;u.onerror=()=>toast('Read-aloud is unavailable. You can follow the picture instead.');speechSynthesis.speak(u)}
function speakStep(){if(state.settings.readAloud)readStep()}
function editRoutine(id){draft=id?structuredClone(routine(id)):{id:uid(),name:'My new routine',icon:'⭐',tone:'morning',steps:[{id:uid(),icon:'⭐',label:'My first step',minutes:3}]};renderEditor()}
function renderEditor(){showModal(`<h2>Make this routine yours</h2><p class="note">Use short, clear steps. All times are adjustable.</p><form id="routine-form"><div class="field"><label for="routine-name">Routine name</label><input id="routine-name" maxlength="60" value="${esc(draft.name)}" required></div><div class="field"><label for="routine-icon">Routine picture</label><select id="routine-icon">${['☀️','🎒','🌙','⭐','🧹','📚','🪥','🌳'].map(i=>`<option ${draft.icon===i?'selected':''}>${i}</option>`).join('')}</select></div><div id="step-list">${draft.steps.map((s,i)=>`<div class="step-edit"><div class="step-fields"><div><label for="icon-${i}">Picture</label><input id="icon-${i}" value="${esc(s.icon)}" maxlength="8" required></div><div><label for="label-${i}">Step ${i+1}</label><input id="label-${i}" value="${esc(s.label)}" maxlength="90" required></div><div><label for="min-${i}">Minutes</label><input type="number" id="min-${i}" value="${s.minutes}" min="1" max="120" required></div></div><div class="step-controls">${button('↑','step-up','small soft',`type="button" data-index="${i}" aria-label="Move step ${i+1} up" ${i===0?'disabled':''}`)}${button('↓','step-down','small soft',`type="button" data-index="${i}" aria-label="Move step ${i+1} down" ${i===draft.steps.length-1?'disabled':''}`)}${button('Remove','step-remove','small icon-btn',`type="button" data-index="${i}" ${draft.steps.length===1?'disabled':''}`)}</div></div>`).join('')}</div><div class="modal-actions"><div class="row">${button('+ Add step','step-add','soft','type="button"')}${routine(draft.id)?button('Delete routine','delete-routine','danger small','type="button"'):''}</div><button class="primary" type="submit">Save routine</button></div></form>`);document.getElementById('routine-form').onsubmit=e=>{e.preventDefault();captureDraft();if(!draft.name.trim()||draft.steps.some(s=>!s.label.trim()||!s.icon.trim()||!Number.isInteger(s.minutes)||s.minutes<1||s.minutes>120))return;const idx=child().routines.findIndex(r=>r.id===draft.id);if(idx<0)child().routines.push(draft);else child().routines[idx]=draft;save();modal.close();render();toast('Routine saved. Ready for your next little step.')};}
function captureDraft(){draft.name=document.getElementById('routine-name').value;draft.icon=document.getElementById('routine-icon').value;draft.steps=draft.steps.map((s,i)=>({...s,icon:document.getElementById(`icon-${i}`).value,label:document.getElementById(`label-${i}`).value,minutes:Number(document.getElementById(`min-${i}`).value)}))}
function confirmDialog(title,text,callback){showModal(`<h2>${esc(title)}</h2><p>${esc(text)}</p><div class="row">${button('Cancel','close','soft')}<button class="primary" id="confirm-yes">Confirm</button></div>`);document.getElementById('confirm-yes').onclick=()=>{modal.close();callback()}}
function addChild(){showModal('<h2>A routine space of their own</h2><form id="add-child-form"><div class="field"><label for="new-name">Child’s nickname</label><input id="new-name" maxlength="35" required autocomplete="off"></div><button class="primary" type="submit">Create profile</button></form>');document.getElementById('add-child-form').onsubmit=e=>{e.preventDefault();const name=document.getElementById('new-name').value.trim();if(!name)return;const c=makeChild(name);state.children.push(c);state.selected=c.id;save();modal.close();render();toast('Profile created with three starter routines.')}}
function addReward(){showModal('<h2>A little thing to look forward to</h2><form id="reward-form"><div class="field"><label for="reward-name">Reward</label><input id="reward-name" placeholder="Choose a bedtime story" maxlength="70" required></div><div class="field"><label for="reward-cost">Stars needed</label><input id="reward-cost" type="number" value="10" min="1" max="1000" required></div><button class="primary" type="submit">Add reward</button></form>');document.getElementById('reward-form').onsubmit=e=>{e.preventDefault();const name=document.getElementById('reward-name').value.trim(),cost=Number(document.getElementById('reward-cost').value);if(!name||!Number.isInteger(cost)||cost<1||cost>1000)return;child().rewards.push({id:uid(),name,cost,icon:'🎁'});save();modal.close();render()}}
function exportBackup(){const blob=new Blob([JSON.stringify({...state,session:null},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Little-Steps-Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup exported. Keep it somewhere safe.')}
function validate(d){
 const str=(s,max=200)=>typeof s==='string'&&s.length>0&&s.length<=max;
 const num=(n,max=1000000)=>Number.isInteger(n)&&n>=0&&n<=max;
 const bad=()=>{throw Error('Invalid backup')};
 const safeId=s=>typeof s==='string'&&/^[a-zA-Z0-9_-]{1,200}$/.test(s);
 if(!d||d.version!==1||!Array.isArray(d.children)||!d.children.length||d.children.length>30||!d.settings||typeof d.settings.timer!=='boolean'||typeof d.settings.readAloud!=='boolean')bad();
 const ids=new Set();for(const c of d.children){if(!safeId(c.id)||ids.has(c.id)||!str(c.name,35)||!num(c.stars)||!Array.isArray(c.routines)||c.routines.length>100||!Array.isArray(c.earned)||!c.earned.every(x=>str(x,500))||!Array.isArray(c.history)||!Array.isArray(c.rewards)||!Array.isArray(c.redemptions))bad();ids.add(c.id);const rid=new Set();for(const r of c.routines){if(!safeId(r.id)||rid.has(r.id)||!str(r.name,60)||!str(r.icon,8)||!['morning','afternoon','evening'].includes(r.tone)||!Array.isArray(r.steps)||!r.steps.length||r.steps.length>50)bad();rid.add(r.id);const sid=new Set();for(const s of r.steps){if(!safeId(s.id)||sid.has(s.id)||!str(s.label,90)||!str(s.icon,8)||!num(s.minutes,120)||s.minutes<1)bad();sid.add(s.id)}}for(const r of c.rewards)if(!safeId(r.id)||!str(r.name,70)||!str(r.icon,8)||!num(r.cost,1000)||r.cost<1)bad();for(const h of c.history)if(!str(h.date)||!str(h.displayDate)||!str(h.name)||!str(h.routineId)||!num(h.done,50)||!num(h.total,50)||!num(h.stars,50))bad();for(const r of c.redemptions)if(!str(r.name)||!str(r.date))bad();}
 if(!ids.has(d.selected))bad();if(d.session){const s=d.session,c=d.children.find(c=>c.id===s.childId),r=c?.routines.find(r=>r.id===s.routineId);if(!r||c.id!==d.selected||!num(s.index,49)||s.index>=r.steps.length||!num(s.done,50)||!num(s.newStars,50)||!str(s.startedDate)||!Array.isArray(s.completed)||!s.completed.every(x=>str(x))||typeof s.paused!=='boolean'||!Number.isFinite(s.deadline)||!num(s.remaining,100000))bad();}return d;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;switch(a){
 case'navigate':{const go=()=>{view=b.dataset.view;render()};if(b.dataset.view==='settings')gate(go);else go();break}
 case'close':modal.close();break;
 case'new-routine':gate(()=>editRoutine());break;
 case'edit-routine':gate(()=>editRoutine(id));break;
 case'start':start(id);break;
 case'finish':finish=null;view='routines';render();break;
 case'done':advance(true);break;
 case'skip':advance(false);break;
 case'pause':{const s=state.session;s.remaining=seconds();s.paused=!s.paused;s.deadline=Date.now()+s.remaining*1000;s.help=false;save();render();break}
 case'add-time':{const s=state.session;s.remaining=seconds()+60;s.deadline=Date.now()+s.remaining*1000;save();tick();break}
 case'help':{const s=state.session;s.remaining=seconds();s.paused=true;s.help=true;save();render();break}
 case'read':readStep();break;
 case'exit':gate(()=>confirmDialog('Leave this routine?','Stars already earned will stay in your jar. This routine will end.',()=>{state.session=null;if('speechSynthesis'in window)speechSynthesis.cancel();save();render()}));break;
 case'step-up':case'step-down':case'step-remove':case'step-add':{captureDraft();const i=Number(b.dataset.index);if(a==='step-add'){if(draft.steps.length>=50){toast('Keep this routine to 50 steps or fewer.');break}draft.steps.push({id:uid(),icon:'⭐',label:'',minutes:3})}else if(a==='step-remove')draft.steps.splice(i,1);else{const j=i+(a==='step-up'?-1:1);[draft.steps[i],draft.steps[j]]=[draft.steps[j],draft.steps[i]]}renderEditor();break}
 case'delete-routine':{const rid=draft.id;confirmDialog('Delete this routine?','This removes the routine from this child’s profile. Earned stars stay.',()=>{child().routines=child().routines.filter(r=>r.id!==rid);save();render()});break}
 case'add-child':gate(addChild);break;
 case'delete-child':gate(()=>confirmDialog('Remove this child’s profile?','Their routines, stars and progress will be removed. Export a backup first if you want to keep them.',()=>{state.children=state.children.filter(c=>c.id!==state.selected);state.selected=state.children[0].id;save();render()}));break;
 case'add-reward':gate(addReward);break;
 case'remove-reward':gate(()=>confirmDialog('Remove this reward?','Your child’s stars will stay.',()=>{child().rewards=child().rewards.filter(r=>r.id!==id);save();render()}));break;
 case'redeem':gate(()=>{const r=child().rewards.find(r=>r.id===id);if(!r||child().stars<r.cost)return;confirmDialog('Approve this reward?',`${r.name} uses ${r.cost} stars.`,()=>{if(child().stars<r.cost)return;child().stars-=r.cost;child().redemptions.push({name:r.name,date:new Date().toLocaleDateString()});save();render();toast('Reward approved. Enjoy your time together!')})});break;
 case'print':window.print();break;
 case'export':exportBackup();break;
 case'restore':document.getElementById('import-file').click();break;
}});
document.addEventListener('submit',e=>{if(e.target.id==='child-form'){e.preventDefault();const name=document.getElementById('child-name').value.trim();if(name){child().name=name;save();render();toast('Nickname saved.')}}});
document.addEventListener('change',async e=>{const el=e.target;if(el.id==='profile'){state.selected=el.value;parentUnlocked=false;save();render()}if(el.id==='chart-select'){chartId=el.value;render()}if(el.id==='timer-setting'||el.id==='voice-setting'){state.settings[el.id==='timer-setting'?'timer':'readAloud']=el.checked;save()}if(el.id==='import-file'&&el.files[0]){try{if(el.files[0].size>5*1024*1024)throw Error('Too large');const incoming=validate(JSON.parse(await el.files[0].text()));confirmDialog('Replace current profiles and progress?',`Restore ${incoming.children.length} child profile(s) from this backup? Export your current data first if you want to keep it.`,()=>{state=incoming;state.session=null;state.activity=null;loadError=false;save();render();toast('Backup restored.')})}catch(err){toast('This is not a valid Little Steps backup. No data was changed.')}el.value=''}});
render();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'list_routines',title:'List this child’s routines',description:'Read the selected child’s routines without changing progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('No inputs expected');return {child:child().name,routines:child().routines.map(r=>({id:r.id,name:r.name,steps:r.steps.length}))}}});document.modelContext.registerTool({name:'start_routine',title:'Start a routine',description:'Open the selected child’s routine player. Does not mark any task complete.',inputSchema:{type:'object',properties:{routineId:{type:'string'}},required:['routineId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.routineId!=='string'||Object.keys(input).length!==1||!routine(input.routineId))throw Error('Choose an existing routine');if(state.session||state.activity)throw Error('An adventure is already active');start(input.routineId);return {started:true,routineId:input.routineId}}})}catch(e){/* Optional browser capability. */}}
